### ISSUE TITLE
BackgroundService dies if you get a timeout on fetchAndLock

### ISSUE THREAD

**Issue by kimjor** [AMalininHere/camunda-worker-dotnet#19]
I have observed that my service stop processing tasks when I get a timeout on the http call to /external-task/fetchAndLock e.g. during restart of Camunda.
This error can also be reproduced by setting the AsyncResponseTimeout higher than the http client timeout.

It seems that the problem is in ExternalTaskSelector where OperationCanceledExceptions are not caught but, I guess, assumed to be part of the shutdown operation.
A proposed fix would be to also catch OperationCanceledExceptions in ExternalTaskSelector if cancellationToken.IsCancellationRequested is false

**Comment by AMalininHere** [comment]
@kimjor Can you create a pull request to fix this defect?

**Comment by kimjor** [comment]
Sure. But it will be to change `catch (Exception e) when (!(e is OperationCanceledException)` to 
`catch (Exception e) when (!(e is OperationCanceledException) || !cancellationToken.IsCancellationRequested)`

**Comment by AMalininHere** [comment]
I think that checking that exception is instance of `OperationCanceledException` would be unnecessary if we will check `ct.IsCancellationRequested`

**Comment by kimjor** [comment]
That is up to you. I'll make a PR with this
