### ISSUE TITLE
Retry count not handled

### ISSUE THREAD

**Issue by oyhan** [AMalininHere/camunda-worker-dotnet#22]
Hi @AMalininHere 
I'm using your very good library thanks
But one thing I encountered was that all tasks are repeatedly fetching and executing because retry count does not decrease on every execution or I didn't make it to.
Thank you again

**Comment by AMalininHere** [comment]
Hello @oyhan 
Thank you for your feedback.
Can you provide details about your use case? What matters is how you tell the camunda engine to retry processing of a task. This can be done by returning a `FailureResult` and by throwing an exception.
It would be great if you could provide a small example of code for the external task handler and BPMN file to reproduce your problem.

**Comment by oyhan** [comment]
Hi Again 
Sorry for the late answer. I was in a hurry that time I'd cloned your code and fixed it for myself
The problem comes when you send FailureResult but in failure, the result must have to pass the remaining retry count to Camunda API as far as I remember
It's been a while and I must check the code.

**Comment by oyhan** [comment]
Another thing:
Do you make arrange the effect of the `Retries` property of the `HandlerTopics`?
I didn't find any clue in the Builder class

**Comment by AMalininHere** [comment]
Hello!

Current implementation of this library hasn't support for automatic retry management. Retries can be manually managed by providing `Retries` to `FailureResult` with decremented value from `ExternalTask.Retires`. I tried solution like following and as I understand it solves the problem.

```C#
public async Task<IExecutionResult> HandleAsync(ExternalTask externalTask, CancellationToken cancellationToken)
{
    _logger.LogInformation("Got message. {Reties}", externalTask.Retries);

    return new FailureResult("Fail")
    {
        Retries = (externalTask.Retries ?? 5) - 1,
        RetryTimeout = 500,
    };
}
```

On the other hand, you can use your own implementation of `IExecutionResult` that calls `IExternalTaskContext.ReportFailureAsync` with internal management of retry count.
