### ISSUE TITLE
Reading task's extension properties

### ISSUE THREAD

**Issue by bobinskim** [AMalininHere/camunda-worker-dotnet#48]
Hi,

Is it possible to access extension properties of executed tasks? It is returned by fetch-and-lock request when setting includeExtensionProperties parameter.

**Comment by amd989** [comment]
I think I added support for this here #32

**Comment by AMalininHere** [comment]
Hello, @bobinskim! Can you describe in more detail what you mean by extension properties?

**Comment by bobinskim** [comment]
Extension properties are the properties added to a task in the camunda modeler extensions panel. 
These can be useful to supply some additional context on specific tasks to the worker.
See docs example on how to get it with fetch-and-lock [here](https://docs.camunda.org/manual/7.16/reference/rest/external-task/fetch/#example-with-extension-properties)
If it is implemented already as stated by @amd989, I still don't see how can I access values of the properties.

**Comment by AMalininHere** [comment]
@bobinskim hello!
Thank you for your issue. I prepared a PR with support for the described functionality

**Comment by AMalininHere** [comment]
Requested feature is available in new release: https://github.com/AMalininHere/camunda-worker-dotnet/releases/tag/0.13.3
